name: Apply PHP Code Style

on:
    push:
        branches:
            - 'master'
    pull_request:
        paths:
            - '**.php'

jobs:
    php-cs-fixer:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - name: Install
              run: composer install

            - name: Run php-cs-fixer
              run: ./vendor/bin/php-cs-fixer fix

            - name: Get last commit message
              id: last-commit-message
              run: |
                echo "::set-output name=msg::$(git log -1 --pretty=%B)"

            - uses: stefanzweifel/git-auto-commit-action@v4
              id: commit
              with:
                  commit_message: ${{ steps.last-commit-message.outputs.msg }}
                  commit_options:  --amend --no-edit
                  push_options: '--force'
